version: '2'
services:
  api:
    build: .
    restart: always
    labels:
      # password hashed according to https://docs.traefik.io/middlewares/basicauth/#general
      # so: `htpasswd -nb -B <username> <password>` and escaped `$` signs (as `$$`)
      - "traefik.http.routers.tetra-automation-api.rule=PathPrefix(`/api/projects/{project_id}/builds/{build_id}/results`)"
      - "traefik.http.middlewares.basicauth.basicauth.users=$TETRA_USERNAME:$TETRA_PASSWORD"
      - "traefik.http.routers.tetra-automation-api.middlewares=api-stripprefix,basicauth"
  worker:
    build: .
    restart: always
  queue:
    restart: always
  db:
    restart: always
  ui:
    build:
      context: ./ui
    restart: always
